name=EpochTime
version=1.0.0
author=Sara Damiano <sdamiano@stroudcenter.org>
maintainer=Sara Damiano <sdamiano@stroudcenter.org>
sentence=An Arduino library for converting between time in parts as used by core gmtime functions and epoch time.
paragraph=
category=Time
url=https://github.com/EnviroDIY/EpochTime
architectures=*
includes=EpochTime.h
depends=
